import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Pusher from "pusher-js";
import {getMP3FileList} from '../functions/fileList'

export default function Home() {
  const [volume, setVolume] = useState(0.5);

  console.log("volume: ", volume);
  useEffect(() => {
    getMP3FileList()
    var pusher = new Pusher("e8fb826764d9c03dee0b", {
      cluster: "ap4",
    });
    var channel = pusher.subscribe("my-channel");

    channel.bind("my-event", (data) => {
      console.log("Play sound");
    });

    channel.bind("play-url", (data) => {
      const audio = new Audio(data.url);
      audio.volume = parseFloat(volume);
      audio.play();
      console.log("Play url:", data);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <label htmlFor="volume">Volume</label>
      <input
        step="0.1"
        type="range"
        value={volume}
        onChange={(e) => {
          console.log(e);
          setVolume(e.target.value);
        }}
        id="volume"
        name="volume"
        min="0"
        max="1"
      />

      <PlayButton name={"Awkward cricket"} path={"/mp3/Awkward-Cricket.mp3"} />
      <PlayButton name={"I'll be back"} path={"/mp3/ill-be-back.mp3"} />
      <PlayButton name={"MLG Horn"} path={"/mp3/mlg-air-horn.mp3"} />

     </div>
  );
}

const PlayButton = ({name, path}) => {
  return (
    <button
    type="button"
    onClick={async () => {
      const res = await fetch("/api/play-url", {
        method: "POST",
        body: JSON.stringify({ url: path }),
      });
      const json = await res.json();
      console.log(json);
    }}
  >
    {name}
  </button> )
}